// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/codigo/Lexer.flex

package codigo;

import java_cup.runtime.*;
import java.io.*;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\2\u0100\1\u0200\1\u0300\33\u0100\1\u0400\267\u0100\10\u0500"+
    "\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\1\0\1\7\1\10\1\0\1\11\2\0"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\11\21"+
    "\2\0\1\22\1\23\1\24\1\25\1\26\5\27\1\30"+
    "\15\27\1\31\6\27\1\0\1\32\1\0\1\33\1\34"+
    "\1\0\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\27\1\46\1\47\1\27\1\50\1\51"+
    "\1\52\1\27\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\2\27\1\0\1\62\1\0\1\63\6\0\1\3"+
    "\33\0\1\64\35\0\1\65\u01e3\0\1\66\251\0\1\67"+
    "\6\0\1\70\323\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\2\13\1\14\1\15"+
    "\1\16\1\17\1\20\3\21\1\22\1\1\16\21\1\2"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\0"+
    "\1\32\2\0\1\33\1\0\1\34\1\35\1\0\1\36"+
    "\1\0\1\37\1\40\1\41\6\21\1\42\10\21\1\43"+
    "\4\21\1\44\2\21\1\0\1\33\1\0\1\45\11\21"+
    "\1\46\2\21\1\47\1\21\1\50\1\51\10\21\1\52"+
    "\1\53\1\21\1\54\2\21\1\55\1\56\1\57\2\21"+
    "\1\60\3\21\1\61\1\21\1\62\1\63\1\64\2\21"+
    "\1\65\1\66\4\21\1\67\1\70\1\71\1\21\1\72"+
    "\1\73\2\21\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\71\0\162\0\253\0\344\0\71\0\71"+
    "\0\u011d\0\71\0\u0156\0\71\0\u018f\0\u01c8\0\u0201\0\u023a"+
    "\0\u0273\0\u02ac\0\u02e5\0\71\0\71\0\u031e\0\u0357\0\u0390"+
    "\0\71\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6\0\u051f"+
    "\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675\0\u06ae\0\u06e7"+
    "\0\u0720\0\71\0\u0759\0\71\0\71\0\71\0\71\0\71"+
    "\0\344\0\71\0\u0792\0\u07cb\0\71\0\u0804\0\71\0\71"+
    "\0\u083d\0\71\0\u0876\0\71\0\71\0\71\0\u08af\0\u08e8"+
    "\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0"+
    "\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u031e\0\u0c06\0\u0c3f"+
    "\0\u0c78\0\u0cb1\0\u031e\0\u0cea\0\u0d23\0\u0759\0\u07cb\0\u0d5c"+
    "\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb"+
    "\0\u0f24\0\u0f5d\0\u031e\0\u0f96\0\u0fcf\0\u031e\0\u1008\0\u031e"+
    "\0\u031e\0\u1041\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197"+
    "\0\u11d0\0\u031e\0\u031e\0\u1209\0\u031e\0\u1242\0\u127b\0\u031e"+
    "\0\u031e\0\u031e\0\u12b4\0\u12ed\0\u031e\0\u1326\0\u135f\0\u1398"+
    "\0\u031e\0\u13d1\0\u031e\0\u031e\0\u031e\0\u140a\0\u1443\0\u031e"+
    "\0\u031e\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u031e\0\u031e\0\u031e"+
    "\0\u1560\0\u031e\0\u031e\0\u1599\0\u15d2\0\u031e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\2\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\2\1\31\1\32\1\26\1\33\1\34\1\35"+
    "\1\36\1\37\2\26\1\40\1\26\1\41\1\26\1\42"+
    "\1\43\1\44\1\45\1\46\1\26\1\47\1\50\1\26"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\73\0"+
    "\1\3\111\0\1\60\45\0\2\61\1\0\3\61\1\62"+
    "\23\61\1\63\36\61\11\64\1\65\20\64\1\66\36\64"+
    "\13\0\1\67\72\0\1\70\2\0\1\71\1\20\66\0"+
    "\1\72\67\0\1\73\70\0\1\73\1\0\2\20\72\0"+
    "\1\74\70\0\1\75\70\0\1\76\65\0\2\26\5\0"+
    "\3\26\2\0\26\26\27\0\2\26\5\0\3\26\2\0"+
    "\1\26\1\77\24\26\27\0\2\26\5\0\3\26\2\0"+
    "\17\26\1\100\6\26\36\0\3\26\3\0\25\26\27\0"+
    "\2\26\5\0\3\26\2\0\15\26\1\101\1\26\1\102"+
    "\6\26\27\0\2\26\5\0\3\26\2\0\10\26\1\103"+
    "\15\26\27\0\2\26\5\0\3\26\2\0\5\26\1\104"+
    "\7\26\1\105\10\26\27\0\2\26\5\0\3\26\2\0"+
    "\13\26\1\106\1\107\10\26\1\110\27\0\2\26\5\0"+
    "\3\26\2\0\13\26\1\111\1\26\1\112\10\26\27\0"+
    "\2\26\5\0\3\26\2\0\14\26\1\113\11\26\27\0"+
    "\2\26\5\0\3\26\2\0\5\26\1\114\7\26\1\115"+
    "\10\26\27\0\2\26\5\0\3\26\2\0\6\26\1\116"+
    "\13\26\1\117\3\26\27\0\2\26\5\0\3\26\2\0"+
    "\17\26\1\120\6\26\27\0\2\26\5\0\3\26\2\0"+
    "\5\26\1\121\20\26\27\0\2\26\5\0\3\26\2\0"+
    "\21\26\1\122\4\26\27\0\2\26\5\0\3\26\2\0"+
    "\15\26\1\123\10\26\27\0\2\26\5\0\3\26\2\0"+
    "\15\26\1\124\10\26\27\0\2\26\5\0\3\26\2\0"+
    "\10\26\1\125\15\26\7\0\2\51\1\0\66\51\5\126"+
    "\1\3\63\126\50\0\1\61\31\0\1\65\70\0\1\127"+
    "\23\0\2\64\3\0\1\64\5\0\1\64\2\0\1\64"+
    "\1\0\1\64\1\0\1\64\27\0\1\130\72\0\2\131"+
    "\67\0\2\26\5\0\3\26\2\0\13\26\1\132\12\26"+
    "\27\0\2\26\5\0\3\26\2\0\22\26\1\133\3\26"+
    "\27\0\2\26\5\0\3\26\2\0\15\26\1\134\10\26"+
    "\27\0\2\26\5\0\3\26\2\0\5\26\1\135\20\26"+
    "\27\0\2\26\5\0\3\26\2\0\1\26\1\136\24\26"+
    "\27\0\2\26\5\0\3\26\2\0\3\26\1\137\22\26"+
    "\27\0\2\26\5\0\3\26\2\0\24\26\1\140\1\26"+
    "\27\0\2\26\5\0\3\26\2\0\11\26\1\141\6\26"+
    "\1\142\5\26\27\0\2\26\5\0\3\26\2\0\4\26"+
    "\1\143\21\26\27\0\2\26\5\0\3\26\2\0\11\26"+
    "\1\144\14\26\27\0\2\26\5\0\3\26\2\0\15\26"+
    "\1\145\10\26\27\0\2\26\5\0\3\26\2\0\17\26"+
    "\1\146\6\26\27\0\2\26\5\0\3\26\2\0\16\26"+
    "\1\147\2\26\1\150\4\26\27\0\2\26\5\0\3\26"+
    "\2\0\21\26\1\151\4\26\27\0\2\26\5\0\3\26"+
    "\2\0\15\26\1\152\10\26\27\0\2\26\5\0\3\26"+
    "\2\0\21\26\1\153\4\26\27\0\2\26\5\0\3\26"+
    "\2\0\11\26\1\154\14\26\27\0\2\26\5\0\3\26"+
    "\2\0\21\26\1\155\4\26\27\0\2\26\5\0\3\26"+
    "\2\0\5\26\1\156\11\26\1\157\6\26\27\0\2\26"+
    "\5\0\3\26\2\0\11\26\1\160\14\26\27\0\2\26"+
    "\5\0\3\26\2\0\5\26\1\161\20\26\27\0\1\130"+
    "\1\131\67\0\2\26\5\0\3\26\2\0\20\26\1\133"+
    "\5\26\27\0\2\26\5\0\3\26\2\0\5\26\1\162"+
    "\20\26\27\0\2\26\5\0\3\26\2\0\13\26\1\163"+
    "\12\26\27\0\2\26\5\0\3\26\2\0\1\26\1\164"+
    "\24\26\27\0\2\26\5\0\3\26\2\0\17\26\1\165"+
    "\6\26\27\0\2\26\5\0\3\26\2\0\11\26\1\166"+
    "\14\26\27\0\2\26\5\0\3\26\2\0\14\26\1\167"+
    "\11\26\27\0\2\26\5\0\3\26\2\0\6\26\1\170"+
    "\17\26\27\0\2\26\5\0\3\26\2\0\5\26\1\171"+
    "\20\26\27\0\2\26\5\0\3\26\2\0\21\26\1\172"+
    "\4\26\27\0\2\26\5\0\3\26\2\0\1\26\1\173"+
    "\24\26\27\0\2\26\5\0\3\26\2\0\22\26\1\174"+
    "\3\26\27\0\2\26\5\0\3\26\2\0\16\26\1\175"+
    "\7\26\27\0\2\26\5\0\3\26\2\0\16\26\1\176"+
    "\7\26\27\0\2\26\5\0\3\26\2\0\14\26\1\177"+
    "\11\26\27\0\2\26\5\0\3\26\2\0\22\26\1\200"+
    "\3\26\27\0\2\26\5\0\3\26\2\0\16\26\1\201"+
    "\7\26\27\0\2\26\5\0\3\26\2\0\11\26\1\202"+
    "\14\26\27\0\2\26\5\0\3\26\2\0\4\26\1\203"+
    "\21\26\27\0\2\26\5\0\3\26\2\0\14\26\1\204"+
    "\11\26\27\0\2\26\5\0\3\26\2\0\12\26\1\205"+
    "\13\26\27\0\2\26\5\0\3\26\2\0\4\26\1\206"+
    "\21\26\27\0\2\26\5\0\3\26\2\0\21\26\1\207"+
    "\4\26\27\0\2\26\5\0\3\26\2\0\21\26\1\210"+
    "\4\26\27\0\2\26\5\0\3\26\2\0\21\26\1\211"+
    "\4\26\27\0\2\26\5\0\3\26\2\0\22\26\1\212"+
    "\3\26\27\0\2\26\5\0\3\26\2\0\3\26\1\213"+
    "\22\26\27\0\2\26\5\0\3\26\2\0\17\26\1\214"+
    "\6\26\27\0\2\26\5\0\3\26\2\0\14\26\1\215"+
    "\11\26\27\0\2\26\5\0\3\26\2\0\5\26\1\216"+
    "\20\26\27\0\2\26\5\0\3\26\2\0\15\26\1\217"+
    "\10\26\27\0\2\26\5\0\3\26\2\0\21\26\1\220"+
    "\4\26\27\0\2\26\5\0\3\26\2\0\11\26\1\221"+
    "\14\26\27\0\2\26\5\0\3\26\2\0\14\26\1\222"+
    "\11\26\27\0\2\26\5\0\3\26\2\0\7\26\1\223"+
    "\16\26\27\0\2\26\5\0\3\26\2\0\16\26\1\224"+
    "\7\26\27\0\2\26\5\0\3\26\2\0\1\26\1\225"+
    "\24\26\27\0\2\26\5\0\3\26\2\0\13\26\1\226"+
    "\12\26\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5643];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\2\11\1\1\1\11\1\1\1\11"+
    "\7\1\2\11\3\1\1\11\20\1\1\11\1\1\5\11"+
    "\1\0\1\11\2\0\1\11\1\0\2\11\1\0\1\11"+
    "\1\0\3\11\27\1\1\0\1\1\1\0\76\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private PrintWriter logWriter;
    private ArrayList<String> errores = new ArrayList<>();
    public static int errorCount = 0;
    private ArrayList<Token> tokens = new ArrayList<>();

    //Constructor el cual lee el código fuente y escribe un 
    //reporte de tokens con su token,lexema,linea y columna
    public Lexer(Reader in, String outputFile, ArrayList<Token> tokens) throws IOException {
        this(in);
        this.tokens = tokens; //Para guardarlos en el puntero y verlos desde el JFlexCup.java
        logWriter = new PrintWriter(new FileWriter(outputFile));
        logWriter.println("=== ANÁLISIS LÉXICO ===");
        logWriter.println("TOKEN\t\t\tLEXEMA\t\tLINEA\t\tCOLUMNA");
        logWriter.println("----------------------------------------");

        
    }
    
    private Symbol symbol(int type) {
        return symbol(type, null);
    }

    // Este es el que eescribe en el archivo de log en general
    // por cada token con su respectivo nombre, lexema, línea y columna
    private Symbol symbol(int type, Object value) {

    
        if (logWriter != null) {
            String tokenName = getTokenName(type);
            String lexeme = (value != null) ? value.toString() : "";
            logWriter.printf("%-25s\t%-15s\t%d\t%d%n", tokenName, lexeme, yyline + 1, yycolumn + 1);
            tokens.add(new Token(tokenName, lexeme, yyline + 1, yycolumn + 1));
            logWriter.flush();
        }
        return new Symbol(type, yyline, yycolumn, value);
    }
    
    // este metodo lo que hace es aumentar el contador de errores,
    // reportar el error y registrarlo, esto no detiene el programa porque funciona
    // en modo panico
    private void reportError(String message) {
        errorCount++;
        String error = String.format("Error léxico: #%d - Línea %d, Columna %d: %s", errorCount, yyline+1, yycolumn+1, message);
        errores.add(error);

        System.err.println("!!!!" + error);

        if (logWriter != null) {
            logWriter.println(">>> " + error);
            logWriter.flush();
        }
    }

    // Obtenemos la lista de errores
    public ArrayList<String> getErrores() {
        return errores;
    }
    
    // Obtenemos el conteo de errores
    public int getErrorCount() {
        return errorCount;
    }
    
    public boolean hayErrores() {
        return errorCount > 0;
    }
    
 




    private String getTokenName(int type) {
        switch(type) {
            case sym.plus_operator: return "PLUS_OPERATOR";
            case sym.minus_operator: return "MINUS_OPERATOR";
            case sym.multiplication_operator: return "MULT_OPERATOR";
            case sym.division_operator: return "DIV_OPERATOR";
            case sym.int_division_operator: return "INT_DIV_OPERATOR";
            case sym.modulo_operator: return "MOD_OPERATOR";
            case sym.power_operator: return "POWER_OPERATOR";
            case sym.increment_operator: return "INCREMENT";
            case sym.decrement_operator: return "DECREMENT";
            case sym.left_parenthesis: return "LEFT_PAREN";
            case sym.right_parenthesis: return "RIGHT_PAREN";
            case sym.left_block: return "LEFT_BLOCK";
            case sym.right_block: return "RIGHT_BLOCK";
            case sym.assignment_operator: return "ASSIGN";
            case sym.equal_operator: return "EQUAL";
            case sym.not_equal_operator: return "NOT_EQUAL";
            case sym.greater_operator: return "GREATER";
            case sym.less_operator: return "LESS";
            case sym.greater_equal_operator: return "GREATER_EQUAL";
            case sym.less_equal_operator: return "LESS_EQUAL";
            case sym.or_operator: return "OR";
            case sym.and_operator: return "AND";
            case sym.not_operator: return "NOT";
            case sym.comma_keyword: return "COMMA";
            case sym.delimiter: return "DELIMITER";
            case sym.int_literal: return "INT_LITERAL";
            case sym.float_literal: return "FLOAT_LITERAL";
            case sym.bool_literal: return "BOOL_LITERAL";
            case sym.CHAR_LITERAL: return "CHAR_LITERAL"; // Esto es por una prueba
            case sym.STRING_LITERAL: return "STRING_LITERAL"; // esto es por una prueba
            case sym.identifier: return "IDENTIFIER";
            case sym.int_keyword: return "INT";
            case sym.float_keyword: return "FLOAT";
            case sym.bool_keyword: return "BOOL";
            case sym.char_keyword: return "CHAR";
            case sym.string_keyword: return "STRING";
            case sym.void_keyword: return "VOID";
            case sym.principal_keyword: return "PRINCIPAL";
            case sym.let_keyword: return "LET";
            case sym.input_keyword: return "INPUT";
            case sym.output_keyword: return "OUTPUT";
            case sym.loop_keyword: return "LOOP";
            case sym.exit_keyword: return "EXIT";
            case sym.when_keyword: return "WHEN";
            case sym.for_keyword: return "FOR";
            case sym.step_keyword: return "STEP";
            case sym.to_keyword: return "TO";
            case sym.downto_keyword: return "DOWNTO";
            case sym.do_keyword: return "DO";
            case sym.return_keyword: return "RETURN";
            case sym.break_keyword: return "BREAK";
            case sym.decide_keyword: return "DECIDE";
            case sym.elseif_keyword: return "ELIF";
            case sym.else_keyword: return "ELSE";
            case sym.EOF: return "EOF";
            default: return "UNKNOWN";
        }
    }
    
    public void closeLog() {
        if (logWriter != null) {
            logWriter.println("----------------------------------------------------------");
            logWriter.println("=== FIN DEL ANÁLISIS ===");
            if (errorCount > 0) {
                logWriter.println("\n>>> TOTAL DE ERRORES LÉXICOS: " + errorCount);
                logWriter.println("\nLISTA DE ERRORES:");
                for (String error : errores) {
                    logWriter.println("  " + error);
                }
            } else {
                logWriter.println("✓ Sin errores léxicos");
            }
            logWriter.close();
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                closeLog();
    return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { // NO lanza excepción, solo reporta y continúa
        reportError("Caracter ilegal: '" + yytext() + "'");
        // Continúa con el siguiente carácter
            }
          // fall through
          case 61: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 62: break;
          case 3:
            { return symbol(sym.left_exclamation, yytext());
            }
          // fall through
          case 63: break;
          case 4:
            { return symbol(sym.delimiter, yytext());
            }
          // fall through
          case 64: break;
          case 5:
            { return symbol(sym.modulo_operator, yytext());
            }
          // fall through
          case 65: break;
          case 6:
            { return symbol(sym.multiplication_operator, yytext());
            }
          // fall through
          case 66: break;
          case 7:
            { return symbol(sym.plus_operator, yytext());
            }
          // fall through
          case 67: break;
          case 8:
            { return symbol(sym.comma_keyword, yytext());
            }
          // fall through
          case 68: break;
          case 9:
            { return symbol(sym.minus_operator, yytext());
            }
          // fall through
          case 69: break;
          case 10:
            { return symbol(sym.division_operator, yytext());
            }
          // fall through
          case 70: break;
          case 11:
            { return symbol(sym.int_literal, yytext());
            }
          // fall through
          case 71: break;
          case 12:
            { return symbol(sym.less_operator, yytext());
            }
          // fall through
          case 72: break;
          case 13:
            { return symbol(sym.assignment_operator, yytext());
            }
          // fall through
          case 73: break;
          case 14:
            { return symbol(sym.greater_operator, yytext());
            }
          // fall through
          case 74: break;
          case 15:
            { return symbol(sym.right_block, yytext());
            }
          // fall through
          case 75: break;
          case 16:
            { return symbol(sym.and_operator, yytext());
            }
          // fall through
          case 76: break;
          case 17:
            { return symbol(sym.identifier, yytext());
            }
          // fall through
          case 77: break;
          case 18:
            { return symbol(sym.power_operator, yytext());
            }
          // fall through
          case 78: break;
          case 19:
            { return symbol(sym.or_operator, yytext());
            }
          // fall through
          case 79: break;
          case 20:
            { return symbol(sym.right_exclamation, yytext());
            }
          // fall through
          case 80: break;
          case 21:
            { return symbol(sym.left_block, yytext());
            }
          // fall through
          case 81: break;
          case 22:
            { return symbol(sym.not_operator, yytext());
            }
          // fall through
          case 82: break;
          case 23:
            { return symbol(sym.right_parenthesis, yytext());
            }
          // fall through
          case 83: break;
          case 24:
            { return symbol(sym.left_parenthesis, yytext());
            }
          // fall through
          case 84: break;
          case 25:
            { return symbol(sym.not_equal_operator, yytext());
            }
          // fall through
          case 85: break;
          case 26:
            { return symbol(sym.STRING_LITERAL, yytext());
            }
          // fall through
          case 86: break;
          case 27:
            { // Char y string es ais por una prueba
        return symbol(sym.CHAR_LITERAL, yytext());
            }
          // fall through
          case 87: break;
          case 28:
            { return symbol(sym.increment_operator, yytext());
            }
          // fall through
          case 88: break;
          case 29:
            { return symbol(sym.decrement_operator, yytext());
            }
          // fall through
          case 89: break;
          case 30:
            { return symbol(sym.int_division_operator, yytext());
            }
          // fall through
          case 90: break;
          case 31:
            { return symbol(sym.less_equal_operator, yytext());
            }
          // fall through
          case 91: break;
          case 32:
            { return symbol(sym.equal_operator, yytext());
            }
          // fall through
          case 92: break;
          case 33:
            { return symbol(sym.greater_equal_operator, yytext());
            }
          // fall through
          case 93: break;
          case 34:
            { return symbol(sym.do_keyword, yytext());
            }
          // fall through
          case 94: break;
          case 35:
            { return symbol(sym.of_keyword, yytext());
            }
          // fall through
          case 95: break;
          case 36:
            { return symbol(sym.to_keyword, yytext());
            }
          // fall through
          case 96: break;
          case 37:
            { return symbol(sym.float_literal, yytext());
            }
          // fall through
          case 97: break;
          case 38:
            { return symbol(sym.end_keyword, yytext());
            }
          // fall through
          case 98: break;
          case 39:
            { return symbol(sym.for_keyword, yytext());
            }
          // fall through
          case 99: break;
          case 40:
            { return symbol(sym.int_keyword, yytext());
            }
          // fall through
          case 100: break;
          case 41:
            { return symbol(sym.let_keyword, yytext());
            }
          // fall through
          case 101: break;
          case 42:
            { return symbol(sym.bool_literal, yytext());
            }
          // fall through
          case 102: break;
          case 43:
            { return symbol(sym.bool_keyword, yytext());
            }
          // fall through
          case 103: break;
          case 44:
            { return symbol(sym.char_keyword, yytext());
            }
          // fall through
          case 104: break;
          case 45:
            { return symbol(sym.elseif_keyword, yytext());
            }
          // fall through
          case 105: break;
          case 46:
            { return symbol(sym.else_keyword, yytext());
            }
          // fall through
          case 106: break;
          case 47:
            { return symbol(sym.exit_keyword, yytext());
            }
          // fall through
          case 107: break;
          case 48:
            { return symbol(sym.loop_keyword, yytext());
            }
          // fall through
          case 108: break;
          case 49:
            { return symbol(sym.step_keyword, yytext());
            }
          // fall through
          case 109: break;
          case 50:
            { return symbol(sym.void_keyword, yytext());
            }
          // fall through
          case 110: break;
          case 51:
            { return symbol(sym.when_keyword, yytext());
            }
          // fall through
          case 111: break;
          case 52:
            { return symbol(sym.break_keyword, yytext());
            }
          // fall through
          case 112: break;
          case 53:
            { return symbol(sym.float_keyword, yytext());
            }
          // fall through
          case 113: break;
          case 54:
            { return symbol(sym.input_keyword, yytext());
            }
          // fall through
          case 114: break;
          case 55:
            { return symbol(sym.decide_keyword, yytext());
            }
          // fall through
          case 115: break;
          case 56:
            { return symbol(sym.downto_keyword, yytext());
            }
          // fall through
          case 116: break;
          case 57:
            { return symbol(sym.output_keyword, yytext());
            }
          // fall through
          case 117: break;
          case 58:
            { return symbol(sym.return_keyword, yytext());
            }
          // fall through
          case 118: break;
          case 59:
            { return symbol(sym.string_keyword, yytext());
            }
          // fall through
          case 119: break;
          case 60:
            { return symbol(sym.principal_keyword, yytext());
            }
          // fall through
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
